version: "3"
services:
  contributor-learner-frontend:
    build: .
    ports:
      - "8081:4200"
    labels:
      SERVICE_4200_NAME: potentiometer-contributor-learner-frontend
    networks: 
      - authentication-Front-network  

networks:
 authentication-Front-network:
   name: potentiometer-network
   external: true